services:
  - type: web
    name: kanang-alalay-backend
    runtime: node
    plan: free
    
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    
    root_dir: .
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PAYMONGO_SECRET_KEY
        sync: false
      - key: PAYMONGO_PUBLIC_KEY
        sync: false